#服务配置
server:
  port: 8888

  # spring配置
spring:
  # jdbc配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springbootdb?useUnicode=true&characterEncoding=utf8
    username: mango
    password: root5.7.22
  #thymeleaf模板
  thymeleaf:
    mode: HTML
    encoding: UTF-8
    cache: false
  aop:
    auto: true
    proxy-target-class: true
  # mybatis-plus
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.xlx.mpd.system.entity
  typeEnumsPackage:
  global-config:
    #主键类型  AUTO:"数据库ID自增"
    id-type: 0
    #字段策略 NOT_EMPTY:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #数据库大写下划线转换
    capital-mode: true
    #逻辑删除配置
    logic-delete-value: 0
    logic-not-delete-value: 1
    #刷新mapper 调试神器
    refresh-mapper: true
  # 原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

